version: '2'

services:
            
    mrpanel_host:
        image: mrpanel/host
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "9901:80"
        volumes:
            - "./Host-Logs:/app/App_Data/Logs"

    mrpanel_ng:
        image: mrpanel/ng
        ports:
            - "9902:80"